### ISSUE TITLE
SSH-Ports bigger than "short" type are not accepted

### ISSUE THREAD

**Issue by maxhq** [apmasell/tabbedmux#6]
I cannot use a big SSH port numbers like 50000, TabbedMux says _Port is too large_:
https://github.com/apmasell/tabbedmux/blob/1544d22d7bcf4f1d87cbd0639e6f8d6f850bab27/open.vala#L77

Btw. if the port number cannot be parsed, the same error message is used (4 lines above).

**Comment by apmasell** [comment]
Thanks. I've fixed that. It should work now.

**Comment by maxhq** [comment]
That was fast! But shouldn‘t it be uint16? I don‘t know Vala, but as I understand the code thats what the `port_number` gets casted to later on.

**Comment by apmasell** [comment]
`short` and `uint16` should be the same type. It's some C legacy: short isn't required to be a specific size, but it's 16 bits on almost every modern platform and most of the network code wouldn't work if it was smaller, but the C standard doesn't actually make this requirement.
